---
name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Set up dot
        run: sudo apt-get install -y graphviz
        
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build Brighton version with Maven
        run: mvn clean verify
        working-directory: slides
      

      - name: Build JPoint version with Maven
        run: mvn clean verify
        working-directory: slides-jpoint

      - name: Make output directory
        run: mkdir -p output 

      - name: Copy slides
        run: for file in slides*; do cp -r "$file/target/generated-slides" "output/$file"; done    

      - name: Deploy to GitHub Pages
        if: success() && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
